# Generated by Django 2.0.3 on 2018-03-31 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('handphone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(80000000)])),
                ('user_type', models.CharField(max_length=15)),
                ('minister_name', models.CharField(max_length=500)),
                ('profilePicURL', models.CharField(blank=True, max_length=150, null=True)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profilepics')),
                ('decisionTable', models.ImageField(blank=True, upload_to='decisiontables')),
            ],
        ),
        migrations.CreateModel(
            name='authorizationReport',
            fields=[
                ('authorizationID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMOPlanReport',
            fields=[
                ('planID', models.IntegerField(primary_key=True, serialize=False)),
                ('caseID', models.IntegerField()),
                ('crisisName', models.CharField(max_length=250)),
                ('emergencyLevel', models.CharField(max_length=250)),
                ('crisisDescription', models.CharField(max_length=100000)),
                ('planDescription', models.CharField(max_length=100000)),
                ('crsisDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='justificationReport',
            fields=[
                ('justificationID', models.IntegerField(primary_key=True, serialize=False)),
                ('justification', models.CharField(max_length=100000)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoApp.CMOPlanReport')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizationStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('eval_dateTime', models.DateTimeField(auto_now_add=True)),
                ('eval_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('eval_hasComment', models.BooleanField(default=False)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoApp.CMOPlanReport')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='statusReport',
            fields=[
                ('statRepID', models.IntegerField(primary_key=True, serialize=False)),
                ('crisisStatus', models.CharField(max_length=250)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('locationDispatched', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('areaAffected', models.CharField(max_length=250)),
                ('statusDescription', models.CharField(max_length=100000)),
                ('caseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoApp.CMOPlanReport')),
            ],
        ),
        migrations.AddField(
            model_name='authorizationreport',
            name='planID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoApp.CMOPlanReport'),
        ),
    ]
