# Generated by Django 2.0.3 on 2018-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoApp', '0002_auto_20180331_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
